dist: trusty
sudo: required
language: python
python:
  - "3.5"
env:
  - SNAP_CHANNEL="stable"
  - SNAP_CHANNEL="edge"
before_install:
  - sudo apt-get install snapd pwgen -y
  - sudo apt-get remove -qy lxd lxd-client
  - sudo snap refresh core
install:
  - pip install tox-travis
  - sudo snap install lxd --$SNAP_CHANNEL
  - sudo snap install juju --classic --$SNAP_CHANNEL
  - sudo snap install charm --classic --$SNAP_CHANNEL
  - sudo snap install --classic juju-wait --$SNAP_CHANNEL
before_script:
  - sudo addgroup lxd || true
  - sudo usermod -a -G lxd $USER
  - sudo -E sudo -u $USER -E bash -c "/snap/bin/juju bootstrap localhost test"
script:
  - tox -e lint,py35
  - tests/integration.sh
